FreeBSD build fixes.

diff --git a/software/usb_ir/bootstrap/runCmake b/software/usb_ir/bootstrap/runCmake
--- a/software/usb_ir/bootstrap/runCmake
+++ b/software/usb_ir/bootstrap/runCmake
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # remember where we come from
 SOURCE="${BASH_SOURCE[0]}"
@@ -21,7 +21,15 @@ fi
 BUILDDIR=build
 PYPATH=/usr/bin
 QTPATH=/usr/bin
-CMAKE=/usr/bin/cmake
+if test -x /usr/bin/cmake; then
+    CMAKE=/usr/bin/cmake
+elif test -x /usr/local/bin/cmake; then
+    CMAKE=/usr/local/bin/cmake
+else
+    echo "Cannot find cmake" >&2
+    exit 2
+fi
+
 
 # override the defaults w use settings
 if [ -e settings.txt ]; then
