Cleaned up post install post remove Debian scripts. Changed directories as needed in #284

diff --git a/software/usb_ir/packaging/debian/postinst b/software/usb_ir/packaging/debian/postinst
--- a/software/usb_ir/packaging/debian/postinst
+++ b/software/usb_ir/packaging/debian/postinst
@@ -1,16 +1,30 @@
 #!/bin/sh
 set -e
-/usr/sbin/groupadd -f -K GID_MIN=100 -K GID_MAX=500 iguanair
-USERS=`getent passwd|grep iguanair|sed -e 's/\([a-zA-Z]*:\)\(.*\)/\1/g'`
 update-rc.d iguanaIR defaults
 
-if [ "$USERS" != "iguanair:" ] ; then
-echo "Adding user iguananir"
-useradd -d / -g iguanair -K UID_MIN=100 -K UID_MAX=500 -K PASS_MAX_DAYS=-1 -s /bin/false iguanair
+if [ -z "`id -u iguanair 2> /dev/null`" ]; then
+    adduser --system --gecos "iguanair" --group \
+            --no-create-home --disabled-password \
+            --quiet iguanair --home /var/run/iguanaIR || true
 fi
 
-chown iguanair:iguanair /lib/udev/devices/iguanaIR
-mkdir /var/run/iguanaIR 2>/dev/null || true
-touch /lib/udev/rules.d/80-iguanaIR.rules
-chown iguanair:iguanair /var/run/iguanaIR
-#/etc/init.d/udev restart
+if [ -d /lib/udev/devices/iguanaIR ] ; then
+    chown iguanair:iguanair /lib/udev/devices/iguanaIR
+else
+     echo >&2 "Unable to set ownership of /lib/udev/devices/iguanaIR as directory does not exist."
+fi
+
+if [ ! -d /var/run/iguanaIR ]; then
+    mkdir /var/run/iguanaIR
+fi
+
+chown iguanair:iguanair /var/run/iguanaIR    
+
+
+if [ -f /lib/udev/rules.d/80-iguanaIR.rules ]; then
+    touch /lib/udev/rules.d/80-iguanaIR.rules
+else
+    echo >&2 "Unable to touch /lib/udev/rules.d/80-iguanaIR.rules (for udev rescan) because file does not exist."
+fi
+
+
diff --git a/software/usb_ir/packaging/debian/postrm b/software/usb_ir/packaging/debian/postrm
--- a/software/usb_ir/packaging/debian/postrm
+++ b/software/usb_ir/packaging/debian/postrm
@@ -1,5 +1,17 @@
 #!/bin/sh
 set -e
-update-rc.d iguanaIR remove ||true
-rmdir /var/run/iguanaIR 2>/dev/null||true
-userdel iguanair||true
+
+if [ purge = "$1" ]; then
+    update-rc.d iguanaIR remove > /dev/null
+
+    if [ -x "$(command -v deluser)" ]; then
+       deluser --quiet --system iguanair > /dev/null || true
+       delgroup --quiet --system iguanair > /dev/null|| true
+    else
+       echo >&2 "not removing iguanair system account because deluser command was not found"
+    fi
+  
+  rmdir /var/run/iguanaIR 2>/dev/null||true 
+ 
+fi
+
